/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaEstudioFrame.java
 *
 * Created on 14/10/2010, 10:44:05 AM
 */

package delucchigomez.Interfaz;


import delucchigomez.Dominio.FachadaDominio;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Gonzalo
 */
public class AltaEstudioFrame extends javax.swing.JFrame {
    private static AltaEstudioFrame instancia;

    static AltaEstudioFrame getInstance() {
        if (instancia == null)
            instancia = new AltaEstudioFrame();

        return instancia;
    }

    /** Creates new form AltaEstudioFrame */
    private AltaEstudioFrame() {
        initComponents();

        int cantidad = FachadaDominio.getMuestras().size();
        ArrayList<String> estudios = new ArrayList<String>();
        DefaultListModel modelo = new DefaultListModel();
        for (int i=0; i<cantidad; i++){
            modelo.add(i, estudios.get(i).toString());
        }
        ListaMuestras.setModel(modelo);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListaTiposEstudio = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMuestras = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(delucchigomez.DelucchigomezApp.class).getContext().getResourceMap(AltaEstudioFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        ListaTiposEstudio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Test Paternidad", "Test Perentesco", "Test Pertenencia" }));
        ListaTiposEstudio.setName("ListaTiposEstudio"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        ListaMuestras.setName("ListaMuestras"); // NOI18N
        jScrollPane1.setViewportView(ListaMuestras);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListaTiposEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListaTiposEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] muestrasSeleccionadas;
        muestrasSeleccionadas=(String[]) ListaMuestras.getSelectedValues();
        String nombreTest= ListaTiposEstudio.getName().toString();
        if (nombreTest.equalsIgnoreCase("EstudioParentesco")){
            //FachadaDominio.EstudioParentesco("EstudioParentesco", muestrasSeleccionadas[0], muestrasSeleccionadas[1]);
            System.out.print("Estudio Parentesco");
        }
        else
            if(nombreTest.equalsIgnoreCase("EstudioPaternidad")){
                FachadaDominio.altaEstudioPaternidad("EstudioPaternidad", muestrasSeleccionadas[0], muestrasSeleccionadas[1], muestrasSeleccionadas[2]);
        }
        else
            if (nombreTest.equalsIgnoreCase("EstudioPertenencia")){
                //FachadaDominio.altaEstudioPaternidad("EstudioPertenencia", muestrasSeleccionadas[0]);
                System.out.print("Estudio Pertenencia");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaEstudioFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaMuestras;
    private javax.swing.JComboBox ListaTiposEstudio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
