/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaPoblacionFrame.java
 *
 * Created on Oct 11, 2010, 11:29:33 AM
 */

package delucchigomez.Interfaz;

import delucchigomez.Dominio.FachadaDominio;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matias
 */
public class AltaPoblacionFrame extends javax.swing.JFrame {
    private static final int INT_CantidadMicrosatelites = 13;
    HashMap<String, Double[]> valMicro = new HashMap<String, Double[]>();

    private static AltaPoblacionFrame instancia;

    public static AltaPoblacionFrame getInstancia(){
        if (instancia == null)
            instancia = new AltaPoblacionFrame();

        return instancia;
    }
    

    /** Creates new form AltaPoblacionFrame */
    private AltaPoblacionFrame() {
        initComponents();
        
        lblMessage.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlAlelos = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlelos = new javax.swing.JTable();
        btnGuardarAlelos = new javax.swing.JButton();
        pnlMicrosatelites = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMicrosatelites = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(delucchigomez.DelucchigomezApp.class).getContext().getResourceMap(AltaPoblacionFrame.class);
        setTitle(resourceMap.getString("FormAltaPoblacion.title")); // NOI18N
        setName("FormAltaPoblacion"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        lblMessage.setForeground(resourceMap.getColor("lblMessage.foreground")); // NOI18N
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setName("lblMessage"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pnlAlelos.setName("pnlAlelos"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblAlelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Porcentaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAlelos.setName("tblAlelos"); // NOI18N
        jScrollPane2.setViewportView(tblAlelos);
        tblAlelos.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblAlelos.columnModel.title0")); // NOI18N
        tblAlelos.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblAlelos.columnModel.title1")); // NOI18N

        pnlAlelos.setViewportView(jScrollPane2);

        btnGuardarAlelos.setText(resourceMap.getString("btnGuardarAlelos.text")); // NOI18N
        btnGuardarAlelos.setName("btnGuardarAlelos"); // NOI18N
        btnGuardarAlelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlelosActionPerformed(evt);
            }
        });

        pnlMicrosatelites.setName("pnlMicrosatelites"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblMicrosatelites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CSF1PO", null, null},
                {"FGA", null, null},
                {"TH01", null, null},
                {"TPOX", null, null},
                {"VWA", null, null},
                {"D3S1358", null, null},
                {"D5S818", null, null},
                {"D7S820", null, null},
                {"D8S1179", null, null},
                {"D13S317", null, null},
                {"D16S539", null, null},
                {"D18S51", null, null},
                {"D21S11", null, null}
            },
            new String [] {
                "Microsatélite", "Mínimo", "Máximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMicrosatelites.setName("tblMicrosatelites"); // NOI18N
        tblMicrosatelites.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMicrosatelites);
        tblMicrosatelites.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblMicrosatelites.columnModel.title0")); // NOI18N
        tblMicrosatelites.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N
        tblMicrosatelites.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title3")); // NOI18N

        txtNombre.setText(resourceMap.getString("txtNombre.text")); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N

        btnGuardar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout pnlMicrosatelitesLayout = new javax.swing.GroupLayout(pnlMicrosatelites);
        pnlMicrosatelites.setLayout(pnlMicrosatelitesLayout);
        pnlMicrosatelitesLayout.setHorizontalGroup(
            pnlMicrosatelitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMicrosatelitesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMicrosatelitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMicrosatelitesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlMicrosatelitesLayout.setVerticalGroup(
            pnlMicrosatelitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMicrosatelitesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlMicrosatelitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlMicrosatelites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlAlelos, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardarAlelos)))
                            .addComponent(jLabel1))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(pnlAlelos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarAlelos)
                        .addGap(27, 27, 27))
                    .addComponent(pnlMicrosatelites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(lblMessage))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private boolean datosValidos(){
    if (txtNombre.getText().trim().equals(""))
        return false;

    for (int i = 0; i < tblMicrosatelites.getRowCount(); i++){
        if (tblMicrosatelites.getValueAt(i, 1) == null){
            String key = tblMicrosatelites.getValueAt(i, 0).toString();
            lblMessage.setText("No se ingreso un valor para " + key);
            lblMessage.setVisible(true);
            return false;
        }
    }
    return true;
}

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        HashMap<String, Integer[]> rangoMicro = new HashMap<String, Integer[]>();
        for (int i=0; i<tblMicrosatelites.getRowCount();i++){
            String nombreMicro = tblMicrosatelites.getValueAt(i, 0).toString();
            Integer[] rango = new Integer[2];
            rango[0]=(Integer)tblMicrosatelites.getValueAt(i, 1);
            rango[1]=(Integer)tblMicrosatelites.getValueAt(i, 2);
            rangoMicro.put(nombreMicro, rango);
        }

        FachadaDominio.altaPoblacion(txtNombre.getText().trim(), rangoMicro, valMicro);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modeloTabla = new DefaultTableModel();

        modeloTabla.addColumn("Numero");
        modeloTabla.addColumn("Porcentaje");

        Integer min = (Integer)tblMicrosatelites.getValueAt((Integer)tblMicrosatelites.getSelectedRow(), 1);
        Integer max = (Integer)tblMicrosatelites.getValueAt((Integer)tblMicrosatelites.getSelectedRow(), 2);

        Integer largo = max - min;

        for(Integer i = 0; i <= largo; i++){
            Integer[] rowData = new Integer[]{min + i,0};
            modeloTabla.addRow(rowData);
        }



        tblAlelos.setModel(modeloTabla);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarAlelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlelosActionPerformed
     
        for (int i=0; i<tblAlelos.getRowCount();i++){
            Double[] numeroPorcentaje = new Double[2];
            numeroPorcentaje[0]= (Double)(tblAlelos.getValueAt(i, 0));
            numeroPorcentaje[1]=(Double)tblAlelos.getValueAt(i, 1);

            int filaNombreMicro=tblMicrosatelites.getSelectedRow();
            String nombreMicro=tblMicrosatelites.getValueAt(filaNombreMicro, 0).toString();
            valMicro.put(nombreMicro, numeroPorcentaje);
        }
    }//GEN-LAST:event_btnGuardarAlelosActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPoblacionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarAlelos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JScrollPane pnlAlelos;
    private javax.swing.JPanel pnlMicrosatelites;
    private javax.swing.JTable tblAlelos;
    private javax.swing.JTable tblMicrosatelites;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
